In [1]:
import pandas as pd

pd.__version__

'2.3.3'

# reading the file excel file for operation

In [ ]:
df=pd.read_excel(r'C:\Users\Pramod\OneDrive\AI Python\Senapati Sir\Document\18th_Pandas\data.xlsx')
df

#to open a excel file install below libraries

#pip install openpyel

df.shape # row and column for dataframe

len(df)
df

df.sum()

df.columns[0][::]

df.isnull

df.isnull().sum()

df=pd.read_excel(r'C:\Users\Pramod\OneDrive\AI Python\Senapati Sir\Document\18th_Pandas\data.xlsx')
df

df.isna().sum()

type(df)

df.info()

df.head()

df.tail()
df.sum()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CountryName    195 non-null    object
 1   CountryCode    195 non-null    object
 2   BirthRate      195 non-null    float64
 3   InternetUsers  195 non-null    float64
 4   IncomeGroup    195 non-null    object
dtypes: float64(2), object(3)
memory usage: 7.7+ KB

,CountryName,CountryCode,BirthRate,InternetUsers,IncomeGroup
0,Aruba,ABW,10.244,78.9,High income
1,Afghanistan,AFG,35.253,5.9,Low income
2,Angola,AGO,45.985,19.1,Upper middle income
3,Albania,ALB,12.877,57.2,Upper middle income
4,United Arab Emirates,ARE,11.044,88.0,High income

# slicing of the df

In [25]:
df[::-1]
df.columns

df.isnull

<bound method DataFrame.isnull of               CountryName CountryCode  BirthRate  InternetUsers  \
0                   Aruba         ABW     10.244           78.9
1             Afghanistan         AFG     35.253            5.9
2                  Angola         AGO     45.985           19.1
3                 Albania         ALB     12.877           57.2
4    United Arab Emirates         ARE     11.044           88.0
..                    ...         ...        ...            ...
190           Yemen, Rep.         YEM     32.947           20.0
191          South Africa         ZAF     20.850           46.5
192      Congo, Dem. Rep.         COD     42.394            2.2
193                Zambia         ZMB     40.471           15.4
194              Zimbabwe         ZWE     35.715           18.5

             IncomeGroup
0            High income
1             Low income
2    Upper middle income
3    Upper middle income
4            High income
..                   ...
190  Lower middle income
191  Upper middle income
192           Low income
193  Lower middle income
194           Low income

[195 rows x 5 columns]>

In [ ]:
df[10:20]
df.describe()
df.head(10)
fg=df[['CountryName','BirthRate']]
len(df.columns)
df.describe().T
df.columns

KeyError: "None of [Index(['CountryName', 'BirthRate'], dtype='object')] are in the [columns]"

In [78]:
df.columns = ['a','b','c','d','e']
df[:]

df.columns=['CountryCode','CountryName','BirthRate','InternetUser','IncomeGroup']
df
df.head(1)

df[['CountryCode','CountryName']][4:8]

            CountryCode CountryName
4  United Arab Emirates         ARE
5             Argentina         ARG
6               Armenia         ARM
7   Antigua and Barbuda         ATG

In [89]:
df['CountryName']

df['NewColumn']=df.BirthRate*df.InternetUser
df.head(1)
df=df.drop('NewColumn',axis=1)
df
df.InternetUser<2
df[df.InternetUser<2]
df[df.BirthRate>40]
g=df.InternetUser>2
d=df.BirthRate>40
df[g*d]

,CountryCode,CountryName,BirthRate,InternetUser,IncomeGroup
2,Angola,AGO,45.985,19.1,Upper middle income
14,Burkina Faso,BFA,40.551,9.1,Low income
65,"Gambia, The",GMB,42.525,14.0,Low income
115,Mali,MLI,44.138,3.5,Low income
128,Nigeria,NGA,40.045,38.0,Lower middle income
167,Chad,TCD,45.745,2.3,Low income
178,Uganda,UGA,43.474,16.2,Low income
192,"Congo, Dem. Rep.",COD,42.394,2.2,Low income
193,Zambia,ZMB,40.471,15.4,Lower middle income